# Generated by Django 3.2.5 on 2021-07-28 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('productImg', models.ImageField(upload_to='media/products', verbose_name='Product Image')),
                ('price', models.IntegerField()),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('Kitchen Appliances', 'Kitchen Appliances'), ('Electronics and Accessories', 'Electronics & Accessories'), ('Sports & Outdoors', 'Sports & Outdoors'), ('Kids and Toys', 'Kids and Toys'), ('Health & Beauty', 'Health & Beauty'), ('Groceries & Foods', 'Groceries and Foods'), ('Fashion', 'Fashion')], max_length=100)),
                ('ratings', models.DecimalField(decimal_places=2, max_digits=3)),
            ],
        ),
    ]
