# Generated by Django 3.2.5 on 2021-07-29 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Kitchen Appliances', 'Kitchen Appliances'), ('Electronics and Accessories', 'Electronics & Accessories'), ('Sports & Outdoors', 'Sports & Outdoors'), ('Kids and Toys', 'Kids and Toys'), ('Health & Beauty', 'Health & Beauty'), ('Groceries & Foods', 'Groceries and Foods'), ('Fashion', 'Fashion')], max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='productImg',
            field=models.ImageField(upload_to='products', verbose_name='Product Image'),
        ),
        migrations.AlterField(
            model_name='product',
            name='ratings',
            field=models.DecimalField(decimal_places=1, max_digits=3),
        ),
    ]
